[wokwi]
version = 1
mcu = "esp32"
elf = ".pio/build/uno/firmware.elf"
firmware = ".pio/build/uno/firmware.hex"

[connections.phantomio]
# Enable PhantomIO for serial and telemetry
enabled = true
port = "serial"
